name: bakwan
description: "A flutter project for daily activity and money tracker"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.2.0

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: 5.9.0
  get: 4.6.6
  google_fonts: 4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
